https://help.github.com/cn/github/authenticating-to-github
https://www.runoob.com/markdown/md-paragraph.html

# 4 NumPy基础

In [74]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [75]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 49 ms


In [76]:
%time for _ in range(10): my_list2 = [x *2 for x in my_list]

Wall time: 2.52 s


## 4.1 NumPy ndarray: 多维数组对象

In [77]:
import numpy as np
# 生成随机数组
data = np.random.randn(2,3)

In [78]:
data

array([[ 2.85548721, -0.87122095, -0.36395267],
       [-1.07443416, -0.73498224,  0.92045056]])

In [79]:
data *10

array([[ 28.55487213,  -8.71220945,  -3.6395267 ],
       [-10.74434157,  -7.34982237,   9.20450559]])

In [80]:
data + data

array([[ 5.71097443, -1.74244189, -0.72790534],
       [-2.14886831, -1.46996447,  1.84090112]])

In [81]:
data.shape

(2, 3)

In [82]:
data.dtype

dtype('float64')

### 4.1.1 生成ndarray

In [83]:
data1 = [6, 7.5, 8 , 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [84]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2    ## 形成了二维数组

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
arr1.dtype


dtype('float64')

In [86]:
arr2.dtype

dtype('int32')

In [87]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [89]:
# empty可以创建一个没有初始化数值得数组，有时可能返回未初始化得垃圾数值
np.empty((2,3,2))

array([[[2.20687562e-312, 2.35541533e-312],
        [0.00000000e+000, 0.00000000e+000],
        [2.20687562e-312, 2.35541533e-312]],

       [[0.00000000e+000, 0.00000000e+000],
        [2.35541533e-312, 2.05833592e-312],
        [2.05833592e-312, 2.35541533e-312]]])

In [90]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 4.1.2 ndarray的数据类型

In [91]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [92]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [93]:
float_arr = arr.astype(np.float32)
float_arr.dtype
float_arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [94]:
arr = np.array([3.7, -1.2, -2.6, 0.5])
arr

array([ 3.7, -1.2, -2.6,  0.5])

In [95]:
arr.astype(np.int32)

array([ 3, -1, -2,  0])

In [96]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype= np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [97]:
# 也可以使用另一个数组的dtype属性
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50],dtype= np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 补充知识
类型	字符代码  
***
bool	?, b1  
int8	b, i1  
uint8	B, u1  
int16	h, i2  
uint16	H, u2  
int32	i, i4  
uint32	I, u4  
int64	q, i8  
uint64	Q, u8  
float16	f2, e  
float32	f4, f  
float64	f8, d  
complex64	F4, F  
complex128	F8, D  
str	a, S（可以在S后面添加数字，表示字符串长度，比如S3表示长度为三的字符串，不写则为最大长度）  
unicode	U  
object	O  
void	V  

In [98]:
# 也可也使用类型代码来传入数据类型
empty_uint32 = np.empty(8,dtype='l') # u4 指uint32
empty_uint32

array([-1717986918,  1074633113,   858993459,  1072902963,  -858993459,
        1074056396,           0,  1071644672])

### 4.1.3 NumPy数组算术

In [99]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [100]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [101]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [102]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [103]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [104]:
arr2 = np.array([[0.,4.,1.,],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [105]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 4.1.4 基础索引与切片

In [106]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr[5]

5

In [108]:
arr[5:8]

array([5, 6, 7])

In [109]:
# 数值被传递给了整个切片，并不是复制
arr[5:8]= 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [110]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [111]:
# 改变arr_slice,变化也会体现在原数组上： 
arr_slice[1]= 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [112]:
# 不写切片值将会引用数组的所有值：
arr_slice[:]= 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [113]:
# 显式地复制数组
arr_slice = arr[5:8].copy()
arr_slice

array([64, 64, 64])

In [114]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [115]:
arr2d[0][2]

3

In [116]:
arr2d[0,2]

3

In [146]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [147]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
old_values = arr3d[0].copy()
arr3d[0] = 42  # 标量和数组都可以传递给arr3d[0]
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [149]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
arr3d[1,0]

array([7, 8, 9])

In [151]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [152]:
x[0] # 以上的数组子集选择中，返回的数组都是视图

array([7, 8, 9])

#### 4.1.4.1 数组的切片索引

In [153]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [154]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [155]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
arr2d[:2] 

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [158]:
arr2d[1,:2]

array([4, 5])

In [159]:
arr2d[:2,2]

array([3, 6])

In [160]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [161]:
arr2d[:2,1:]= 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 4.1.5 布尔索引

In [163]:
names = np.array(['Bob','Joe','Will',"Bob",'Will','Joe','Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [171]:
data

array([[-1.28460242, -0.53479872, -0.42927983,  0.53418445],
       [ 1.31033713,  0.24649015, -0.28226544,  0.2938887 ],
       [ 0.23374365, -1.70166064, -0.51548093,  0.78940541],
       [-0.4716249 , -0.92869037, -2.57371775, -1.46525801],
       [ 0.93270108,  1.5272894 , -0.76878659,  0.09909037],
       [-1.4686996 , -0.61388458,  0.74798024,  0.65432083],
       [ 0.36322767,  2.73594203,  2.86051602,  3.20169854]])

In [172]:
# 比较names数组和字符串'Bob'会产生一个布尔值数组
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [173]:
# 索引数组时可以传入布尔值数组 
# 布尔值数组的长度必须和数组轴索引长度一致，长度不正确时，该方法并不会报错
data [names == 'Bob']

array([[-1.28460242, -0.53479872, -0.42927983,  0.53418445],
       [-0.4716249 , -0.92869037, -2.57371775, -1.46525801]])

In [181]:
data[names =='Bob', 2:]

array([[-0.42927983,  0.53418445],
       [-2.57371775, -1.46525801]])

In [183]:
data[names == 'Bob', 3]

array([ 0.53418445, -1.46525801])

In [184]:
mask =(names == 'Bob') | (names == 'Will')
mask 

array([ True, False,  True,  True,  True, False, False])

## 8.1 分层索引

In [117]:
import numpy as np
import pandas as pd

In [118]:
data = pd.Series(np.random.randn(9),
        index=[['a','a','a','b','b','c','c','d','d'],
        [1,2,3,1,3,1,2,2,3]])

In [119]:
data

a  1    0.805060
   2    0.302912
   3    1.999137
b  1    1.151559
   3   -0.004998
c  1    0.966459
   2    0.073297
d  2   -1.066252
   3    0.403401
dtype: float64

In [120]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [121]:
data.loc[['b','d']]

b  1    1.151559
   3   -0.004998
d  2   -1.066252
   3    0.403401
dtype: float64

In [122]:
data.loc[:,2]

a    0.302912
c    0.073297
d   -1.066252
dtype: float64

In [123]:
data.unstack()

1         2         3
a  0.805060  0.302912  1.999137
b  1.151559       NaN -0.004998
c  0.966459  0.073297       NaN
d       NaN -1.066252  0.403401

In [124]:
data.unstack().stack()

a  1    0.805060
   2    0.302912
   3    1.999137
b  1    1.151559
   3   -0.004998
c  1    0.966459
   2    0.073297
d  2   -1.066252
   3    0.403401
dtype: float64

In [125]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), index=[['a',         'a','b','b'], [1,2,1,2]], columns=[['Ohio','Ohio',               'Colarado'],['Green','Red','Green']])
frame

Ohio     Colarado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [126]:
frame.index.names = ['key1','key2']
frame.columns.names = ['state','color']
frame

state      Ohio     Colarado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [127]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [128]:
frame.index

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['key1', 'key2'])

前面介绍的带有层级名称的DataFrame的列可以这样创建：MultiIndex.from_arrays([['Ohio','Ohio','Colorado'],['Green','Red','Green']],names=['state','color'])

### 8.1.3 使用DataFrame的列进行索引

In [129]:
frame = pd.DataFrame({'a': range(7),'b': range(7,0,-1),
            'c': ['one','one','one','two','two','two','two'],               'd': [0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [130]:
frame2 = frame.set_index(['c','d'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [131]:
frame.set_index(['c','d'], drop=0)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [132]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

## 8.2 联合与合并数据集

In [133]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1': range(7)})
df2 = pd.DataFrame({'key':['a','b','d'],'data2': range(3)})

In [134]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [135]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [136]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [137]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [138]:
df3 = pd.DataFrame({'lkey': ['b','b','b','c','a','a','b'],                         'data1': range(7)})
df3

lkey  data1
0    b      0
1    b      1
2    b      2
3    c      3
4    a      4
5    a      5
6    b      6

In [139]:
df4 = pd.DataFrame({'rkey': ['a','b','d'],'data2': range(3)})
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [140]:
pd.merge(df3,df4,left_on= 'lkey', right_on= 'rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      2    b      1
3    b      6    b      1
4    a      4    a      0
5    a      5    a      0

In [141]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [142]:
df1 = pd.DataFrame({'key': ['b','b','a','c','a','b'], 'data1': range(6)})
df2 = pd.DataFrame({'key': ['a','b','a','b','d'], 'data2': range(5)})

In [143]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [144]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [145]:
pd.merge(df1, df2, on='key', how='left') # how to merge?

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0