In [ ]:
https://help.github.com/cn/github/authenticating-to-github
https://www.runoob.com/markdown/md-paragraph.html

# 4 NumPy基础

In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 39 ms


In [4]:
%time for _ in range(10): my_list2 = [x *2 for x in my_list]

Wall time: 1.8 s


## 4.1 NumPy ndarray: 多维数组对象

In [5]:
import numpy as np
# 生成随机数组
data = np.random.randn(2,3)

In [6]:
data

array([[-1.02174097,  0.42292336, -0.61556085],
       [-1.31112766, -1.14770538,  0.71629616]])

In [7]:
data *10

array([[-10.21740973,   4.22923362,  -6.15560851],
       [-13.11127661, -11.47705377,   7.16296162]])

In [8]:
data + data

array([[-2.04348195,  0.84584672, -1.2311217 ],
       [-2.62225532, -2.29541075,  1.43259232]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

### 4.1.1 生成ndarray

In [11]:
data1 = [6, 7.5, 8 , 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2    ## 形成了二维数组

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr1.dtype


dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
# empty可以创建一个没有初始化数值得数组，有时可能返回未初始化得垃圾数值
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 4.1.2 ndarray的数据类型

In [19]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [55]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [54]:
float_arr = arr.astype(np.float32)
float_arr.dtype
float_arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [56]:
arr = np.array([3.7, -1.2, -2.6, 0.5])
arr

array([ 3.7, -1.2, -2.6,  0.5])

In [57]:
arr.astype(np.int32)

array([ 3, -1, -2,  0])

In [58]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype= np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [61]:
# 也可以使用另一个数组的dtype属性
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50],dtype= np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 补充知识
类型	字符代码  
***
bool	?, b1  
int8	b, i1  
uint8	B, u1  
int16	h, i2  
uint16	H, u2  
int32	i, i4  
uint32	I, u4  
int64	q, i8  
uint64	Q, u8  
float16	f2, e  
float32	f4, f  
float64	f8, d  
complex64	F4, F  
complex128	F8, D  
str	a, S（可以在S后面添加数字，表示字符串长度，比如S3表示长度为三的字符串，不写则为最大长度）  
unicode	U  
object	O  
void	V  

In [72]:
# 也可也使用类型代码来传入数据类型
empty_uint32 = np.empty(8,dtype='l') # u4 指uint32
empty_uint32

array([1043144745, 1852788256,  773864037, 1678388782, 1696622181,
       1885692792, 1869572212, 2037655659])

### 4.1.3 NumPy数组算术

In [73]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [74]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [75]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [76]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [77]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [78]:
arr2 = np.array([[0.,4.,1.,],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [79]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 4.1.4 基础索引与切片

In [80]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr[5]

5

In [82]:
arr[5:8]

array([5, 6, 7])

In [84]:
# 数值被传递给了整个切片，并不是复制
arr[5:8]= 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [85]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [86]:
# 改变arr_slice,变化也会体现在原数组上： 
arr_slice[1]= 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [87]:
# 不写切片值将会引用数组的所有值：
arr_slice[:]= 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [88]:
# 显式地复制数组
arr_slice = arr[5:8].copy()
arr_slice

array([64, 64, 64])

## 8.1 分层索引

In [20]:
import numpy as np
import pandas as pd

In [21]:
data = pd.Series(np.random.randn(9),
        index=[['a','a','a','b','b','c','c','d','d'],
        [1,2,3,1,3,1,2,2,3]])

In [22]:
data

a  1    0.183970
   2    1.404415
   3   -0.806107
b  1    0.591952
   3   -1.165483
c  1   -0.873591
   2   -0.308894
d  2   -0.469364
   3   -0.208555
dtype: float64

In [23]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [24]:
data.loc[['b','d']]

b  1    0.591952
   3   -1.165483
d  2   -0.469364
   3   -0.208555
dtype: float64

In [25]:
data.loc[:,2]

a    1.404415
c   -0.308894
d   -0.469364
dtype: float64

In [26]:
data.unstack()

1         2         3
a  0.183970  1.404415 -0.806107
b  0.591952       NaN -1.165483
c -0.873591 -0.308894       NaN
d       NaN -0.469364 -0.208555

In [27]:
data.unstack().stack()

a  1    0.183970
   2    1.404415
   3   -0.806107
b  1    0.591952
   3   -1.165483
c  1   -0.873591
   2   -0.308894
d  2   -0.469364
   3   -0.208555
dtype: float64

In [28]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), index=[['a',         'a','b','b'], [1,2,1,2]], columns=[['Ohio','Ohio',               'Colarado'],['Green','Red','Green']])
frame

Ohio     Colarado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [29]:
frame.index.names = ['key1','key2']
frame.columns.names = ['state','color']
frame

state      Ohio     Colarado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [30]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [31]:
frame.index

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['key1', 'key2'])

前面介绍的带有层级名称的DataFrame的列可以这样创建：MultiIndex.from_arrays([['Ohio','Ohio','Colorado'],['Green','Red','Green']],names=['state','color'])

### 8.1.3 使用DataFrame的列进行索引

In [32]:
frame = pd.DataFrame({'a': range(7),'b': range(7,0,-1),
            'c': ['one','one','one','two','two','two','two'],               'd': [0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [33]:
frame2 = frame.set_index(['c','d'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [34]:
frame.set_index(['c','d'], drop=0)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [35]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

## 8.2 联合与合并数据集

In [36]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1': range(7)})
df2 = pd.DataFrame({'key':['a','b','d'],'data2': range(3)})

In [37]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [38]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [39]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [40]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [41]:
df3 = pd.DataFrame({'lkey': ['b','b','b','c','a','a','b'],                         'data1': range(7)})
df3

lkey  data1
0    b      0
1    b      1
2    b      2
3    c      3
4    a      4
5    a      5
6    b      6

In [42]:
df4 = pd.DataFrame({'rkey': ['a','b','d'],'data2': range(3)})
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [43]:
pd.merge(df3,df4,left_on= 'lkey', right_on= 'rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      2    b      1
3    b      6    b      1
4    a      4    a      0
5    a      5    a      0

In [44]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [45]:
df1 = pd.DataFrame({'key': ['b','b','a','c','a','b'], 'data1': range(6)})
df2 = pd.DataFrame({'key': ['a','b','a','b','d'], 'data2': range(5)})

In [46]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [47]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [48]:
pd.merge(df1, df2, on='key', how='left') # how to merge?

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0