# 4 NumPy基础

In [32]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [42]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 26.9 ms


In [44]:
%time for _ in range(10): my_list2 = [x *2 for x in my_list]

Wall time: 898 ms


## 4.1 NumPy ndarray: 多维数组对象

In [61]:
import numpy as np
# 生成随机数组
data = np.random.randn(2,3)

In [62]:
data

array([[ 0.27427822, -0.32252241,  0.50560885],
       [-1.12511067, -0.04459116,  1.13344794]])

In [63]:
data *10

array([[  2.74278221,  -3.22522411,   5.05608854],
       [-11.25110672,  -0.44591161,  11.33447942]])

In [64]:
data + data

array([[ 0.54855644, -0.64504482,  1.01121771],
       [-2.25022134, -0.08918232,  2.26689588]])

In [65]:
data.shape

(2, 3)

In [66]:
data.dtype

dtype('float64')

### 4.1.1 生成ndarray

## 8.1 分层索引

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.Series(np.random.randn(9),
        index=[['a','a','a','b','b','c','c','d','d'],
        [1,2,3,1,3,1,2,2,3]])

In [4]:
data

a  1   -1.042661
   2   -0.481548
   3    1.848089
b  1   -0.615618
   3   -2.612314
c  1   -0.071103
   2    0.314060
d  2   -0.703251
   3    0.361683
dtype: float64

In [5]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [6]:
data.loc[['b','d']]

b  1   -0.615618
   3   -2.612314
d  2   -0.703251
   3    0.361683
dtype: float64

In [7]:
data.loc[:,2]

a   -0.481548
c    0.314060
d   -0.703251
dtype: float64

In [8]:
data.unstack()

1         2         3
a -1.042661 -0.481548  1.848089
b -0.615618       NaN -2.612314
c -0.071103  0.314060       NaN
d       NaN -0.703251  0.361683

In [9]:
data.unstack().stack()

a  1   -1.042661
   2   -0.481548
   3    1.848089
b  1   -0.615618
   3   -2.612314
c  1   -0.071103
   2    0.314060
d  2   -0.703251
   3    0.361683
dtype: float64

In [10]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), index=[['a',         'a','b','b'], [1,2,1,2]], columns=[['Ohio','Ohio',               'Colarado'],['Green','Red','Green']])
frame

Ohio     Colarado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [11]:
frame.index.names = ['key1','key2']
frame.columns.names = ['state','color']
frame

state      Ohio     Colarado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [12]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [13]:
frame.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           names=['key1', 'key2'])

前面介绍的带有层级名称的DataFrame的列可以这样创建：MultiIndex.from_arrays([['Ohio','Ohio','Colorado'],['Green','Red','Green']],names=['state','color'])

### 8.1.3 使用DataFrame的列进行索引

In [14]:
frame = pd.DataFrame({'a': range(7),'b': range(7,0,-1),
            'c': ['one','one','one','two','two','two','two'],               'd': [0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [15]:
frame2 = frame.set_index(['c','d'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [16]:
frame.set_index(['c','d'], drop=0)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [17]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

## 8.2 联合与合并数据集

In [18]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1': range(7)})
df2 = pd.DataFrame({'key':['a','b','d'],'data2': range(3)})

In [19]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [20]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [21]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [22]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [23]:
df3 = pd.DataFrame({'lkey': ['b','b','b','c','a','a','b'],                         'data1': range(7)})
df3

lkey  data1
0    b      0
1    b      1
2    b      2
3    c      3
4    a      4
5    a      5
6    b      6

In [24]:
df4 = pd.DataFrame({'rkey': ['a','b','d'],'data2': range(3)})
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [25]:
pd.merge(df3,df4,left_on= 'lkey', right_on= 'rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      2    b      1
3    b      6    b      1
4    a      4    a      0
5    a      5    a      0

In [26]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [27]:
df1 = pd.DataFrame({'key': ['b','b','a','c','a','b'], 'data1': range(6)})
df2 = pd.DataFrame({'key': ['a','b','a','b','d'], 'data2': range(5)})

In [28]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [29]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [30]:
pd.merge(df1, df2, on='key', how='left') # how to merge?

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0